package main

import (
	"mobiniqow/handlers"

	"github.com/gin-gonic/gin"
	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
)

var router *gin.Engine

// @title Blueprint Swagger API
// @version 1.0
// @description Swagger API for Golang Project Blueprint.
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email martin7.heinz@gmail.com
// @license.name MIT
// @license.url https://github.com/MartinHeinz/go-project-blueprint/blob/master/LICENSE
// @BasePath /api/v1
func main() {
	router = gin.New()
	initRoute()
	router.Run(":2900") // listen and serve on 0.0.0.0:8080 (for windows "localhost:8080")
}

func initRoute() {
	// Group persons related routes together
	//router.Use(CORSMiddleware())

	//database migration

	coinRoutes := router.Group("/coins/:wname")
	{
		coinRoutes.GET("/", handlers.GetCoin)
		coinRoutes.POST("/coins", handlers.CreateCoin)
		coinRoutes.PUT("/:symbol", handlers.UpdateCoin)
		coinRoutes.DELETE("/:symbol", handlers.DeleteCoin)
	}
	walletRoutes := router.Group("/wallets")
	{
		walletRoutes.POST("/", handlers.CreateWallet)
		walletRoutes.GET("/", handlers.GetWallet)
		walletRoutes.PUT("/:wname", handlers.UpdateWallet)
		walletRoutes.DELETE("/:wname", handlers.DeleteWallet)
	}
}
